---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: starter
  secretRef:
    name: fluxauth
  url: https://github.com/azure/caf-terraform-landingzones-starter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./enterprise_scale/construction_sets/aks/online/aks_secure_baseline/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
