archetype_definitions:
  root:
    archetype_id: root
    policy_assignments:
      Allowed-Locations:
        listOfAllowedLocations:
          - southeastasia
          - eastasia
      Deny-RSG-Locations:
        listOfAllowedLocations:
          - southeastasia
          - eastasia
      Deploy-ASC-Monitoring:
      Deploy-ASC-Defender:
        emailSecurityContact: change_me@contoso.com
        logAnalytics:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
        pricingTierVMs: Standard
        pricingTierSqlServers: Free
        pricingTierAppServices: Free
        pricingTierStorageAccounts: Free
        pricingTierSqlServerVirtualMachines: Free
        pricingTierKubernetesService: Standard
        pricingTierContainerRegistry: Free
        pricingTierKeyVaults: Standard
        pricingTierDns: Free
        pricingTierArm: Free
      Deploy-AzActivity-Log:
        logAnalytics:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
      Deploy-LX-Arc-Monitoring:
      Deploy-Resource-Diag:
        profileName: eslz-diagnostic-log
        logAnalytics:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
      Deploy-VM-Monitoring:
        logAnalytics_1:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
      Deploy-VMSS-Monitoring:
        logAnalytics_1:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
    policy_definitions:
      Append-AppService-httpsonly:
      Append-AppService-latestTLS:
      Append-KV-SoftDelete:
      Append-Redis-disableNonSslPort:
      Append-Redis-sslEnforcement:
      Deny-AA-child-resources:
      Deny-AppGW-Without-WAF:
      Deny-AppServiceApiApp-http:
      Deny-AppServiceFunctionApp-http:
      Deny-AppServiceWebApp-http:
      Deny-MySql-http:
      Deny-PostgreSql-http:
      Deny-Private-DNS-Zones:
      Deny-PublicEndpoint-Aks:
      Deny-PublicEndpoint-CosmosDB:
      Deny-PublicEndpoint-KeyVault:
      Deny-PublicEndpoint-MariaDB:
      Deny-PublicEndpoint-MySQL:
      Deny-PublicEndpoint-PostgreSql:
      Deny-PublicEndpoint-Sql:
      Deny-PublicEndpoint-Storage:
      Deny-PublicIP:
      Deny-RDP-From-Internet:
      Deny-Redis-http:
      Deny-Sql-minTLS:
      Deny-SqlMi-minTLS:
      Deny-Storage-minTLS:
      Deny-VNET-Peer-Cross-Sub:
      Deny-VNet-Peering:
      Deploy-ASC-Defender-ACR:
      Deploy-ASC-Defender-AKS:
      Deploy-ASC-Defender-AKV:
      Deploy-ASC-Defender-AppSrv:
      Deploy-ASC-Defender-ARM:
      Deploy-ASC-Defender-DNS:
      Deploy-ASC-Defender-SA:
      Deploy-ASC-Defender-Sql:
      Deploy-ASC-Defender-SQLVM:
      Deploy-ASC-Defender-VMs:
      Deploy-ASC-SecurityContacts:
      Deploy-Budget:
      Deploy-DDoSProtection:
      Deploy-Diagnostics-AA:
      Deploy-Diagnostics-ACI:
      Deploy-Diagnostics-ACR:
      Deploy-Diagnostics-ActivityLog:
      Deploy-Diagnostics-AKS:
      Deploy-Diagnostics-AnalysisService:
      Deploy-Diagnostics-ApiForFHIR:
      Deploy-Diagnostics-APIMgmt:
      Deploy-Diagnostics-ApplicationGateway:
      Deploy-Diagnostics-Batch:
      Deploy-Diagnostics-CDNEndpoints:
      Deploy-Diagnostics-CognitiveServices:
      Deploy-Diagnostics-CosmosDB:
      Deploy-Diagnostics-Databricks:
      Deploy-Diagnostics-DataExplorerCluster:
      Deploy-Diagnostics-DataFactory:
      Deploy-Diagnostics-DataLakeStore:
      Deploy-Diagnostics-DLAnalytics:
      Deploy-Diagnostics-EventGridSub:
      Deploy-Diagnostics-EventGridSystemTopic:
      Deploy-Diagnostics-EventGridTopic:
      Deploy-Diagnostics-EventHub:
      Deploy-Diagnostics-ExpressRoute:
      Deploy-Diagnostics-Firewall:
      Deploy-Diagnostics-FrontDoor:
      Deploy-Diagnostics-Function:
      Deploy-Diagnostics-HDInsight:
      Deploy-Diagnostics-iotHub:
      Deploy-Diagnostics-KeyVault:
      Deploy-Diagnostics-LoadBalancer:
      Deploy-Diagnostics-LogicAppsISE:
      Deploy-Diagnostics-LogicAppsWF:
      Deploy-Diagnostics-MariaDB:
      Deploy-Diagnostics-MediaService:
      Deploy-Diagnostics-MlWorkspace:
      Deploy-Diagnostics-MySQL:
      Deploy-Diagnostics-NetworkSecurityGroups:
      Deploy-Diagnostics-NIC:
      Deploy-Diagnostics-PostgreSQL:
      Deploy-Diagnostics-PowerBIEmbedded:
      Deploy-Diagnostics-RecoveryVault:
      Deploy-Diagnostics-RedisCache:
      Deploy-Diagnostics-Relay:
      Deploy-Diagnostics-SearchServices:
      Deploy-Diagnostics-ServiceBus:
      Deploy-Diagnostics-SignalR:
      Deploy-Diagnostics-SQLDBs:
      Deploy-Diagnostics-SQLElasticPools:
      Deploy-Diagnostics-SQLMI:
      Deploy-Diagnostics-StreamAnalytics:
      Deploy-Diagnostics-TimeSeriesInsights:
      Deploy-Diagnostics-TrafficManager:
      Deploy-Diagnostics-VirtualNetwork:
      Deploy-Diagnostics-VM:
      Deploy-Diagnostics-VMSS:
      Deploy-Diagnostics-VNetGW:
      Deploy-Diagnostics-WebServerFarm:
      Deploy-Diagnostics-Website:
      Deploy-Diagnostics-WVDAppGroup:
      Deploy-Diagnostics-WVDHostPools:
      Deploy-Diagnostics-WVDWorkspace:
      Deploy-DNSZoneGroup-For-Blob-PrivateEndpoint:
      Deploy-DNSZoneGroup-For-File-PrivateEndpoint:
      Deploy-DNSZoneGroup-For-KeyVault-PrivateEndpoint:
      Deploy-DNSZoneGroup-For-Queue-PrivateEndpoint:
      Deploy-DNSZoneGroup-For-Sql-PrivateEndpoint:
      Deploy-DNSZoneGroup-For-Table-PrivateEndpoint:
      Deploy-FirewallPolicy:
      Deploy-HUB:
      Deploy-LA-Config:
      Deploy-Log-Analytics:
      Deploy-MySQL-sslEnforcement:
      Deploy-Nsg-FlowLogs-to-LA:
      Deploy-Nsg-FlowLogs:
      Deploy-PostgreSQL-sslEnforcement:
      Deploy-Sql-AuditingSettings:
      Deploy-SQL-minTLS:
      Deploy-Sql-SecurityAlertPolicies:
      Deploy-Sql-Tde:
      Deploy-Sql-vulnerabilityAssessments:
      Deploy-SqlMi-minTLS:
      Deploy-Storage-sslEnforcement:
      Deploy-vHUB:
      Deploy-VNET-HubSpoke:
      Deploy-vNet:
      Deploy-vWAN:
      Deploy-Windows-DomainJoin:
    policy_set_definitions:
      Deny-PublicEndpoints:
      Deploy-ASC-Config:
      Deploy-Diag-LogAnalytics:
      Deploy-Sql-Security:
      Enforce-Encryption-CMK:
      Enforce-EncryptTransit:
  landing-zones:
    archetype_id: landing-zones
    policy_assignments:
      Deny-IP-Forwarding:
      Deny-RDP-From-Internet:
      Deny-Storage-http:
      Deploy-AKS-Policy:
      Deploy-SQL-DB-Auditing:
      Deploy-SQL-Security:
      Deny-Priv-Escalation-AKS:
      Deny-Priv-Containers-AKS:
      Deny-http-Ingress-AKS:
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - subscription_creation_landingzones
  connectivity:
    archetype_id: platform_connectivity
    role_definitions:
      CAF-network-vhub-peering:
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - connectivity
        '[contoso-CONNECTIVITY] CAF-network-vhub-peering':
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - subscription_creation_landingzones
  management:
    archetype_id: platform_management
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - management
  identity:
    archetype_id: platform_identity
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - identity
  decommissioned:
    archetype_id: platform_decommissioned
  platform:
    archetype_id: platform
  sandboxes:
    archetype_id: platform_sandboxes