apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: terraform-azurerm-caf-runnerdeploy
spec:
  replicas: 2
  template:
    metadata: 
      labels:
        aadpodidbinding: podmi-github-runner
    spec:
      repository: aztfmod/terraform-azurerm-caf
      env: []