scenario:
  name: demo
  deployment_mode: interactive
  # automated_deployment (manual | e2e | pipelines)
  automated_deployment: e2e
features:
  subscription_creation: false
  enterprise_scale: false
  # Define the Azure Active Directory options ( none | msi | sp). msi and sp requires Azure AD groups rw.
  azuread_identity_mode: none

# cleanup_destination - recommended to clean and recreated a clean state from template.
cleanup_destination: true
remote_install_path: /tf/caf/contoso/demo
tenant_name: terraformdev
caf_landingzone_branch: 2107.1
sku:
  keyvault: standard

billing_subscription_role_delegations:
  billing_account_name: 123456677
  enrollment_account_name: 4332445
launchpad:
  passthrough: "false"
  inherit_tags: "false"
  random_length: 5
  caf_environment: sandpit
  account_replication_type: GRS
  default_region: region1
  # number_of_levels defines the number of levels to configure. Recommended is 4 or 5
  number_of_levels: 5
  regions:
    region1: southeastasia
    region2: eastasia
  tags:
    ApplicationOwner: CAF_demo
    deploymentType: Terraform
    costCenter: 0
    BusinessUnit: SHARED
    DR: NON-DR-ENABLED
tfstates:
  launchpad:
    lz_key_name: launchpad
    tfstate: caf_launchpad.tfstate
  billing_subscription_role_delegations:
    lz_key_name: billing_subscription_role_delegations
    tfstate: billing_subscription_role_delegations.tfstate
