- name: Clean-up directory
  file:
    path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
    state: absent
  when: config.cleanup_destination | bool

- name: Creates directory
  file:
    path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
    state: directory

- name: readme
  ansible.builtin.template:
    src: "{{ level }}/{{ base_folder }}/readme.md"
    dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/readme.md"
    force: yes

- name: management
  ansible.builtin.template:
    src: "{{ level }}/{{ base_folder }}/{{ item }}.tfvars.j2"
    dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item }}.tfvars"
    force: yes
  loop:
    - automation_account
    - diagnostic_log_analytics
    - diagnostic_storage_accounts
    - diagnostics_definition
    - diagnostics_destinations
    - landingzone
    - resource_groups
    - servicehealth