- name: "[{{ level }}-{{ base_folder }}] - Set variables"
  set_fact: 
    destination_path: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}"
    subscription_key: launchpad_credentials

- name: "[{{ level }}-{{ base_folder }}] - Load variable for launchpad"
  include_vars:
    name: resources
    dir: "{{config_folder}}"
    depth: 1
    ignore_unknown_extensions: true
    files_matching: "launchpad_credentials.yaml"

- debug:
    msg: "{{resources}}"

- name: "[{{ level }}-{{ base_folder }}] Clean-up directory"
  file:
    path: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}"
    state: absent
  when: config.configuration_folders.platform.cleanup_destination | bool

- name: "[{{ level }}-{{ base_folder }}] Creates directory"
  file:
    path: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}"
    state: directory

#
# resource_groups
#
- name: "[{{ level }}-{{ base_folder }}] - resource_groups"
  when: 
    - resources.subscriptions[subscription_key].resource_groups is defined
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ resource_template_folder }}/resource_groups.tfvars.j2"
  

- name: "[{{ level }}-{{ base_folder }}] generate configuration files."
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/*.tfvars.j2"

- name: "[{{ level }}-{{ base_folder }}] deploy."
  when: boostrap_launchpad | bool
  shell: |
    /tf/rover/rover.sh \
      -lz /tf/caf/landingzones/caf_solution \
      -var-folder {{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }} \
      -tfstate_subscription_id {{ config.caf_terraform.launchpad.subscription_id }} \
      -target_subscription {{ config.caf_terraform.launchpad.subscription_id }} \
      -tfstate {{ config.tfstates.platform.launchpad_credentials.tfstate }} \
      -launchpad \
      -log-severity {{ config.gitops.rover_log_error }} \
      -env {{ config.caf_terraform.launchpad.caf_environment }} \
      -level {{ level }} \
      -a apply
  args:
    warn: no

- debug:
    msg: "{{ keyvaults.cred_subscription_creation_platform.vault_uri }}"
  when: credentials_tfstate_exists.rc == 0

- name: "[{{ level }}-{{ base_folder }}] generate configuration files."
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/*.md"
