archetype_definitions:
  root:
    archetype_id: root
    policy_assignments:
      Allowed-Locations:
        listOfAllowedLocations:
          - southeastasia<replace>
          - eastasia<replace>
      Deny-RSG-Locations:
        listOfAllowedLocations:
          - southeastasia<replace>
          - eastasia<replace>
      Deploy-ASC-Monitoring:
      Deploy-ASCDF-Config:
        emailSecurityContact: <replace>
        logAnalytics:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
        enableAscForKubernetes: DeployIfNotExists
        enableAscForSql: Disabled
        enableAscForSqlOnVm: Disabled
        enableAscForDns: Disabled
        enableAscForArm: Disabled
        enableAscForOssDb: Disabled
        enableAscForAppServices: Disabled
        enableAscForRegistries: DeployIfNotExists
        enableAscForKeyVault: DeployIfNotExists
        enableAscForStorage: Disabled
        enableAscForServers: DeployIfNotExists
      Deploy-AzActivity-Log:
        logAnalytics:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
      Deploy-LX-Arc-Monitoring:
      Deploy-Resource-Diag:
        profileName: eslz-diagnostic-log
        logAnalytics:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
      Deploy-VM-Monitoring:
        logAnalytics_1:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
      Deploy-VMSS-Monitoring:
        logAnalytics_1:
          lz_key: management
          output_key: diagnostics
          resource_type: log_analytics
          resource_key: central_logs_sea
          attribute_key: id
    policy_definitions:
      Append-AppService-httpsonly:
      Append-AppService-latestTLS:
      Append-KV-SoftDelete:
      Append-Redis-disableNonSslPort:
      Append-Redis-sslEnforcement:
      Audit-MachineLearning-PrivateEndpointId:
      Deny-AA-child-resources:
      Deny-AppGW-Without-WAF:
      Deny-AppServiceApiApp-http:
      Deny-AppServiceFunctionApp-http:
      Deny-AppServiceWebApp-http:
      Deny-Databricks-NoPublicIp:
      Deny-Databricks-Sku:
      Deny-Databricks-VirtualNetwork:
      Deny-MachineLearning-Aks:
      Deny-MachineLearning-Compute-SubnetId:
      Deny-MachineLearning-Compute-VmSize:
      Deny-MachineLearning-ComputeCluster-RemoteLoginPortPublicAccess:
      Deny-MachineLearning-ComputeCluster-Scale:
      Deny-MachineLearning-HbiWorkspace:
      Deny-MachineLearning-PublicAccessWhenBehindVnet:
      Deny-MachineLearning-PublicNetworkAccess:
      Deny-MySql-http:
      Deny-PostgreSql-http:
      Deny-Private-DNS-Zones:
      Deny-PublicEndpoint-MariaDB:
      Deny-PublicIP:
      Deny-RDP-From-Internet:
      Deny-Redis-http:
      Deny-Sql-minTLS:
      Deny-SqlMi-minTLS:
      Deny-Storage-minTLS:
      Deny-Subnet-Without-Nsg:
      Deny-Subnet-Without-Udr:
      Deny-VNET-Peer-Cross-Sub:
      Deny-VNet-Peering:
      Deploy-ASC-SecurityContacts:
      Deploy-Budget:
      Deploy-Custom-Route-Table:
      Deploy-DDoSProtection:
      Deploy-Diagnostics-AA:
      Deploy-Diagnostics-ACI:
      Deploy-Diagnostics-ACR:
      Deploy-Diagnostics-AnalysisService:
      Deploy-Diagnostics-ApiForFHIR:
      Deploy-Diagnostics-APIMgmt:
      Deploy-Diagnostics-ApplicationGateway:
      Deploy-Diagnostics-CDNEndpoints:
      Deploy-Diagnostics-CognitiveServices:
      Deploy-Diagnostics-CosmosDB:
      Deploy-Diagnostics-Databricks:
      Deploy-Diagnostics-DataExplorerCluster:
      Deploy-Diagnostics-DataFactory:
      Deploy-Diagnostics-DLAnalytics:
      Deploy-Diagnostics-EventGridSub:
      Deploy-Diagnostics-EventGridSystemTopic:
      Deploy-Diagnostics-EventGridTopic:
      Deploy-Diagnostics-ExpressRoute:
      Deploy-Diagnostics-Firewall:
      Deploy-Diagnostics-FrontDoor:
      Deploy-Diagnostics-Function:
      Deploy-Diagnostics-HDInsight:
      Deploy-Diagnostics-iotHub:
      Deploy-Diagnostics-LoadBalancer:
      Deploy-Diagnostics-LogicAppsISE:
      Deploy-Diagnostics-MariaDB:
      Deploy-Diagnostics-MediaService:
      Deploy-Diagnostics-MlWorkspace:
      Deploy-Diagnostics-MySQL:
      Deploy-Diagnostics-NetworkSecurityGroups:
      Deploy-Diagnostics-NIC:
      Deploy-Diagnostics-PostgreSQL:
      Deploy-Diagnostics-PowerBIEmbedded:
      Deploy-Diagnostics-RedisCache:
      Deploy-Diagnostics-Relay:
      Deploy-Diagnostics-SignalR:
      Deploy-Diagnostics-SQLElasticPools:
      Deploy-Diagnostics-SQLMI:
      Deploy-Diagnostics-TimeSeriesInsights:
      Deploy-Diagnostics-TrafficManager:
      Deploy-Diagnostics-VirtualNetwork:
      Deploy-Diagnostics-VM:
      Deploy-Diagnostics-VMSS:
      Deploy-Diagnostics-VNetGW:
      Deploy-Diagnostics-WebServerFarm:
      Deploy-Diagnostics-Website:
      Deploy-Diagnostics-WVDAppGroup:
      Deploy-Diagnostics-WVDHostPools:
      Deploy-Diagnostics-WVDWorkspace:
      Deploy-FirewallPolicy:
      Deploy-MySQL-sslEnforcement:
      Deploy-Nsg-FlowLogs-to-LA:
      Deploy-Nsg-FlowLogs:
      Deploy-PostgreSQL-sslEnforcement:
      Deploy-Sql-AuditingSettings:
      Deploy-SQL-minTLS:
      Deploy-Sql-SecurityAlertPolicies:
      Deploy-Sql-Tde:
      Deploy-Sql-vulnerabilityAssessments:
      Deploy-SqlMi-minTLS:
      Deploy-Storage-sslEnforcement:
      Deploy-Windows-DomainJoin:
    policy_set_definitions:
      Deny-PublicPaaSEndpoints:
      Deploy-ASCDF-Config:
      Deploy-Diagnostics-LogAnalytics:
      Deploy-Sql-Security:
      Enforce-Encryption-CMK:
      Enforce-EncryptTransit:
  landing-zones:
    archetype_id: landing-zones
    policy_assignments:
      Deny-IP-Forwarding:
      Deny-Priv-Containers-AKS:
      Deny-Priv-Escalation-AKS:
      Deny-RDP-From-Internet:
      Deny-Storage-http:
      Deploy-AKS-Policy:
      Deploy-SQL-DB-Auditing:
      Deploy-SQL-Threat:
      Enable-DDoS-VNET:
      Enforce-AKS-HTTPS:
      Enforce-TLS-SSL:
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - subscription_creation_landingzones
  connectivity:
    archetype_id: platform_connectivity
    policy_assignments:
      Enable-DDoS-VNET:
    role_definitions:
      CAF-network-vhub-peering:
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - connectivity
        '[<replace>-CONNECTIVITY] CAF-network-vhub-peering':
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - subscription_creation_landingzones
  management:
    archetype_id: platform_management
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - management
  identity:
    archetype_id: platform_identity
    policy_assignments:
      Deny-RDP-From-Internet:
      Deny-Public-IP:
    archetype_config:
      access_control:
        Owner:
          azuread_groups:
            lz_key: launchpad
            attribute_key: id
            resource_keys:
              - identity
  decommissioned:
    archetype_id: platform_decommissioned
  platform:
    archetype_id: platform
  sandboxes:
    archetype_id: platform_sandboxes