#
# Level 0
#
- name: launchpad
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: launchpad
    level: level0

  tasks:
    - import_tasks: "{{ level }}/launchpad/{{ model }}.yaml"


- name: billing_subscription_role_delegations
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: launchpad
    level: level0

  tasks:
    - import_tasks: "{{ level }}/billing_subscription_role_delegations/{{ model }}.yaml"
      when: config.features.subscription_creation | bool

#
# Level 1
#
- name: Generate config - level1 - management
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: management
    level: level1

  tasks:
    - import_tasks: "{{ level }}/management/{{ model }}.yaml"


- name: Generate config - level1 - GitOps Azure DevOps Bootstrap
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: gitops/azuredevops/bootstrap
    level: level1

  tasks:
    - import_tasks: "{{ level }}/gitops/azuredevops/bootstrap/{{ model }}.yaml"



- name: Generate config - level1 - Projects GitOpsProd
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: gitops/azuredevops/projects/gitopsprod
    level: level1

  tasks:
    - import_tasks: "{{ level }}/gitops/azuredevops/projects/gitopsprod/{{ model }}.yaml"

- name: Generate config - level1 - ESLZ
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: eslz
    level: level1

  tasks:
    - name: ESLZ - Clean-up directory
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item.path }}"
        state: absent
      with_filetree: "{{ level }}/{{ base_folder }}"
      when:
        - item.state == 'directory'
        - config.features.enterprise_scale == false | bool

    - name: ESLZ - Clean-up base directory
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
        state: absent
      with_filetree: "{{ level }}/{{ base_folder }}"
      when:
        - item.state == 'directory'
        - config.features.enterprise_scale == false | bool

    - import_tasks: "{{ level }}/eslz/{{ scenario }}_{{ model }}.yaml"
      when: config.features.enterprise_scale == true | bool


#
# Level 2
#
- name: Level 2 - Networking
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    connectivity_virtual_wan: "{{ lookup('file', '{{ config_folder }}/connectivity_virtual_wan.yaml') | from_yaml }}"
    connectivity_virtual_hub: "{{ lookup('file', '{{ config_folder }}/connectivity_virtual_hub.yaml') | from_yaml }}"
    connectivity_firewall: "{{ lookup('file', '{{ config_folder }}/connectivity_firewall.yaml') | from_yaml }}"
    connectivity_firewall_policies: "{{ lookup('file', '{{ config_folder }}/connectivity_firewall_policies.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: connectivity
    level: level2
    folders:
      - virtual_wan


  tasks:
    - name: Creates {{ level }} directory
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}"
        state: directory

    - name: Creates {{ base_folder }} directory strcture
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
        state: directory

    - name: "{{ base_folder }} - Readme"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item | basename | regex_replace('.j2$', '') }}"
        force: yes
      with_fileglob:
        - "{{ level }}/{{ base_folder }}/*.md"

    - name: "{{ base_folder }} - Virtual Wan"
      include_tasks: "{{ base_templates_folder }}/{{ level }}/{{ base_folder }}/{{ folder_name }}/{{ model }}.yaml"
      loop:
       - virtual_wan
      loop_control:
        loop_var: folder_name

    - name: Virtual Hubs
      include_tasks: "{{ base_templates_folder }}/{{ level }}/{{ base_folder }}/virtual_hub/{{ model }}.yaml"
      loop: "{{ tfstates.virtual_hubs.keys() }}"
      loop_control:
        loop_var: virtual_hub

    - name: Firewall Policies
      include_tasks: "{{ base_templates_folder }}/{{ level }}/{{ base_folder }}/firewall_policy/{{ model }}.yaml"
      loop: "{{ tfstates.firewall_policies.keys() }}"
      loop_control:
        loop_var: firewall_policy

- name: Level 2 - identity
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    identity: "{{ lookup('file', '{{ config_folder }}/identity.yaml') | from_yaml }}"
    connectivity_virtual_wan: "{{ lookup('file', '{{ config_folder }}/connectivity_virtual_wan.yaml') | from_yaml }}"
    connectivity_virtual_hub: "{{ lookup('file', '{{ config_folder }}/connectivity_virtual_hub.yaml') | from_yaml }}"
    connectivity_firewall: "{{ lookup('file', '{{ config_folder }}/connectivity_firewall.yaml') | from_yaml }}"
    connectivity_firewall_policies: "{{ lookup('file', '{{ config_folder }}/connectivity_firewall_policies.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: identity
    level: level2
    folders:
      - virtual_wan


  tasks:
    - name: Creates {{ level }} directory
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}"
        state: directory

    - name: Creates {{ base_folder }} directory strcture
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
        state: directory

    - name: "{{ base_folder }} - Readme"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item | basename | regex_replace('.j2$', '') }}"
        force: yes
      with_fileglob:
        - "{{ level }}/{{ base_folder }}/*.md"

    - name: "{{ base_folder }} - adds"
      include_tasks: "{{ base_templates_folder }}/{{ level }}/{{ base_folder }}/{{ model }}.yaml"



#
# Pipelines
#
- name: Pipelines
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: pipelines

  tasks:
    - import_tasks: "{{ base_folder }}/{{ model }}.yaml"
    - debug: msg="You can now proceed to the next steps and execute the deployment. Refer to the readme in {{ config.destination_install_path }}{{ config.destination_relative_base_path }}/README.md"
