caf_terraform:
  naming_convention:
    passthrough: false
    inherit_tags: false
    random_length: 5
  launchpad:
    subscription_id: set_subscription_guid
    subscription_name: set_subscription_name
    tenant_id: set_tenant_id
    caf_environment: demo
    account_replication_type: GRS
    blob_versioning_enabled: true
    container_delete_retention_policy: 7
    delete_retention_policy: 7
    default_region_key: region1
    number_of_levels: 5
    regions:
      region1:
        name: Southeast Asia
        slug: sea
    tags:
      ApplicationOwner: CAF_demo
      deploymentType: Terraform
      costCenter: 0
      BusinessUnit: SHARED
      DR: NON-DR-ENABLED

platform_core_setup:
  sku:
    keyvault: standard
  enterprise_scale:
    enable: false
    model: demo
    management_group_name: "simple Demo 001"
    management_group_prefix: demo001
    deploy_core_landing_zones: true
    clean_up_destination_folder: true
    update_lib_folder: true
    subscription_deployment_mode: single_reuse
    enable_azure_subscription_vending_machine: false
    private_lib:
      version_to_deploy: v0.3.3
      v0.1.x:
        caf_landingzone_branch: "2107.1"
      v0.3.3:
        caf_landingzone_branch: eslz.0.3.3

platform_management:
  enable: true
  log_analytics_workspace: create_new
  retention_in_days: 30
  enable_monitoring:
    - Arc
    - VM
    - VMSS

networking_topology:
  enable_ddos_protection_standard: true
  private_dns_zones_for_azure_paas_services: true
  deployment_option: virtual_wan

platform_identity:
  # Set the Azure Active Directory tenant name. Do not include the .onmicrosoft.com
  tenant_name: change_tenant_name
  azuread_identity_mode: logged_in_user
  caf_platform_maintainers:
    - john@contoso.com

# cleanup_destination - recommended to clean and recreated a clean state from template.
configuration_folders:
  platform:
    cleanup_destination: false
    destination_base_path: /tf/caf
    destination_relative_path: configuration/contoso/standalone/platform
  asvm:
    cleanup_destination: false
    destination_base_path: /tf/caf
    destination_relative_path: configuration/contoso/standalone/asvm

notifications:
  service_health_alerts:
    emails:
      support1:
        name: email_alert primary support
        email_address: john@contoso.com
  security_center_email_contact: john@contoso.com

gitops:
  caf_landingzone_branch: "patch.5.4.4"
  deployment_mode: interactive
  rover_log_error: ERROR