- name: Creates {{ base_folder }} directory strcture
  shell: mkdir -p "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}"

- name: "{{ base_folder }} - Readme"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/*.md"

- name: "{{ base_folder }} - Virtual Wan"
  include_tasks: "{{ level }}/{{ base_folder }}/{{ folder_name }}/ansible.yaml"
  loop:
    - virtual_wan
  loop_control:
    loop_var: folder_name

- name: Virtual Hubs
  include_tasks: "{{ level }}/{{ base_folder }}/virtual_hub/ansible.yaml"
  loop: "{{ tfstates.virtual_hubs.keys() }}"
  loop_control:
    loop_var: virtual_hub
    
- name: VPN Sites
  include_tasks: "{{ level }}/{{ base_folder }}/vpn_site/ansible.yaml"
  loop: "{{ tfstates.vpn_sites.keys() }}"
  loop_control:
    loop_var: site

- name: Express Route
  include_tasks: "{{ level }}/{{ base_folder }}/express_route/ansible.yaml"
  loop: "{{ tfstates.express_route_circuits.keys() }}"
  loop_control:
    loop_var: circuit

# - name: Firewall Policies
#   include_tasks: "{{ level }}/{{ base_folder }}/firewall_policy/ansible.yaml"
#   loop: "{{ tfstates.firewall_policies.keys() }}"
#   loop_control:
#     loop_var: firewall_policy