- name: ESLZ - Clean-up directory
  file:
    path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item.path }}"
    state: absent
  with_filetree: "{{ base_folder }}"
  when:
    - item.state == 'directory'
    - config.cleanup_destination | bool

# - name: Creates directory structure
#   file:
#     path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item.path }}"
#     state: directory
#   with_filetree: "{{ base_folder }}"
#   when: item.state == 'directory'

- name: Tfvars
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ base_folder }}/*.j2"
    - "{{ base_folder }}/*.md"
