- name: Express_routes {{ circuit }} - Clean-up directory
  file:
    path: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/express_route/{{ circuit }}"
    state: absent
  when:
    - config.configuration_folders.platform.cleanup_destination | bool

- name: Express_routes {{ circuit }} - Creates directory structure
  file:
    path: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/express_route/{{ circuit }}"
    state: directory

- name: Express_routes {{ circuit }} - variables
  set_fact:
    destination_path_resources: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/express_route/{{ circuit }}"

- name: Express_routes {{ circuit }} - readme
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/express_route/{{ circuit }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/express_route/*.md"

#
# landingzone
#
- name: "[{{ level }}-{{ circuit }}] - express route - landingzone"
  when: 
    - connectivity_express_routes.express_route_circuits is defined
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path_resources }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/express_route/landingzone.tfvars.j2"

#
# azurerm_express_route_circuit_peerings
#
- name: "[{{ level }}-{{ circuit }}] - express route - azurerm_express_route_circuit_peerings"
  when: 
    - connectivity_express_routes.azurerm_express_route_circuit_peerings is defined
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path_resources }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/express_route/azurerm_express_route_circuit_peerings.tfvars.j2"
