#
# Level 2 - Connectivity
#
- name: vwan
  hosts: localhost
  vars:
    config: "{{ lookup('file', '{{ config_folder }}/{{ model }}.yaml') | from_yaml }}"
    connectivity: "{{ lookup('file', '{{ config_folder }}/connectivity.yaml') | from_yaml }}"
    cidr: "{{ lookup('file', '{{ config_folder }}/cidr.yaml') | from_yaml }}"
    tfstates: "{{ lookup('file', '{{ config_folder }}/tfstates.yaml') | from_yaml }}"
    base_templates_folder: /tf/caf/templates/platform
    base_folder: connectivity/virtual_wan
    level: level2

  tasks:
    - name: Creates directory structure
      file:
        path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}"
        state: directory

    - import_tasks: "{{ base_templates_folder }}/{{ level }}/{{ base_folder }}/{{ model }}.yaml"
