apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.1.1
    chart: redis
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
