- name: CAF Terraform - Generate configuration files
  hosts: localhost
  vars:
    base_templates_folder: "{{ base_templates_folder }}/asvm"
    resource_template_folder: "{{ base_templates_folder }}/resources"
    level: level3


  tasks:

    - name: "Load variable for asvm config"
      include_vars:
        name: asvm_config__to_merge
        dir: "{{config_folder}}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "config.asvm.yaml|tfstates.asvm.yaml"

    - name: "Set base variables"
      set_fact:
        job_cache_base_path: "/home/vscode/.terraform.cache"   
        config: "{{asvm_config__to_merge}}"

    - name: "Content of asvm_config__to_merge"
      debug:
        msg: "{{asvm_config__to_merge}}"

    
    - name: "Creates cache directory"
      file:
        path: "{{ job_cache_base_path }}/launchpad"
        state: directory


    - name: "{{ level }} | Get platform details (requires '-e config_folder_platform=path to yamls' path to be set)"
      include_tasks: "ansible-get-platform-details.yaml"
      when: config_folder_platform is defined

#
# Level 3
#

# asvm

    - name: "{{ level }} | Azure Subscription Vending Machine (ASVM)"
      include_tasks: "{{ level }}/ansible.yaml"
      loop: "{{config.tfstates['asvm'].keys()}}"
      loop_control:
        loop_var: asvm_long_folder

#
# Linters
#

    - name: Terraform linter
      shell: |
        terraform fmt -recursive {{ destination_base_path }}
