# Source: aad-pod-identity/templates/mic-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aad-pod-identity-mic
  namespace: default
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: mic
---
# Source: aad-pod-identity/templates/nmi-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aad-pod-identity-nmi
  namespace: default
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: nmi
---
# Source: aad-pod-identity/templates/mic-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aad-pod-identity-mic
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: mic
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: [ "list", "watch" ]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: [ "create", "get", "update"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureidentitybindings", "azureidentities"]
  verbs: ["get", "list", "watch", "post", "update"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azurepodidentityexceptions"]
  verbs: ["list", "update"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureassignedidentities"]
  verbs: ["*"]
---
# Source: aad-pod-identity/templates/nmi-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aad-pod-identity-nmi
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: nmi
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureidentitybindings", "azureidentities", "azurepodidentityexceptions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureassignedidentities"]
  verbs: ["get", "list", "watch"]
---
# Source: aad-pod-identity/templates/mic-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aad-pod-identity-mic
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: mic
subjects:
- kind: ServiceAccount
  name: aad-pod-identity-mic
  namespace: default
roleRef:
  kind: ClusterRole
  name: aad-pod-identity-mic
  apiGroup: rbac.authorization.k8s.io
---
# Source: aad-pod-identity/templates/nmi-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aad-pod-identity-nmi
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: nmi
subjects:
- kind: ServiceAccount
  name: aad-pod-identity-nmi
  namespace: default
roleRef:
  kind: ClusterRole
  name: aad-pod-identity-nmi
  apiGroup: rbac.authorization.k8s.io
---
# Source: aad-pod-identity/templates/nmi-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aad-pod-identity-nmi
  namespace: default
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: nmi
    tier: node
  annotations:
    description: Deploy components for aad-pod-identity
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/instance: aad
      app.kubernetes.io/component: nmi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aad-pod-identity
        app.kubernetes.io/instance: aad
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: aad-pod-identity-4.0.0
        app.kubernetes.io/component: nmi
        tier: node
    spec:
      serviceAccountName: aad-pod-identity-nmi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: iptableslock
      - name: kubelet-config
        hostPath:
          path: /etc/default/kubelet
          type: FileOrCreate
      containers:
      - name: nmi
        image: "mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.7.5"
        imagePullPolicy: Always
        args:
          - "--node=$(NODE_NAME)"
          - --http-probe-port=8085
          - --operation-mode=standard
          - --kubelet-config=/etc/default/kubelet
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FORCENAMESPACED
            value: "false"
        securityContext:
          runAsUser: 0
          capabilities:
            drop:
            - ALL
            add:
            - DAC_READ_SEARCH
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: iptableslock
        - name: kubelet-config
          mountPath: /etc/default/kubelet
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      nodeSelector:
        kubernetes.io/os: linux
---
# Source: aad-pod-identity/templates/mic-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-pod-identity-mic
  namespace: default
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.0.0
    app.kubernetes.io/component: mic
  annotations:
    description: Deploy components for aad-pod-identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/instance: aad
      app.kubernetes.io/component: mic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aad-pod-identity
        app.kubernetes.io/instance: aad
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: aad-pod-identity-4.0.0
        app.kubernetes.io/component: mic
    spec:
      serviceAccountName: aad-pod-identity-mic
      containers:
      - name: mic
        image: "mcr.microsoft.com/oss/azure/aad-pod-identity/mic:v1.7.5"
        imagePullPolicy: Always
        args:
          - "--cloudconfig=/etc/kubernetes/azure.json"
          - "--logtostderr"
        securityContext:
          runAsUser: 0
        env:
          - name: MIC_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FORCENAMESPACED
            value: "false"
        volumeMounts:
          - name: k8s-azure-file
            mountPath: /etc/kubernetes/azure.json
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
      - name: k8s-azure-file
        hostPath:
          path: /etc/kubernetes/azure.json
      nodeSelector:
        kubernetes.io/os: linux
---
# Source: aad-pod-identity/templates/mic-exception.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic
  namespace: default
spec:
  podLabels:
    app: mic
    component: mic
    app.kubernetes.io/component: mic
---
# Source: aad-pod-identity/templates/mic-exception.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: aks-addon-exception
  namespace: kube-system
spec:
  podLabels:
    kubernetes.azure.com/managedby: aks