trigger: none

variables:
  - group: iac-secure-caf

resources:
  containers:
  - container: rover
    image: $(ROVER_IMAGE)
    options: --user 0

stages:
- stage: deploy_lunchpad
  jobs:
  - job: deploy_lunchpad
    displayName: "Deploy Lunchpad"
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Pipeline.Workspace)/* /tf/caf && cp -r $(Pipeline.Workspace)/.devcontainer /tf/caf/                 
            . /tf/caf/enterprise_scale/construction_sets/aks/scripts/launchpad.sh
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: '^1.15'        
      # - name: Test
      #   if: contains(github.event.comment.body, '/deploy-all') || contains(github.event.comment.body, '/deploy-lunchpad') || github.event_name != 'issue_comment'     
      #   run: |
      #       cd /tf/caf/enterprise_scale/construction_sets/aks/test
      #       ./run_test.sh level0_launchpad/launchpad_test.go
