trigger: none

variables:
  - group: iac-secure-caf

resources:
  containers:
  - container: rover
    image: $(ROVER_IMAGE)
    options: --user 0:0 -e TF_PLUGIN_CACHE_DIR="/home/vsts_azpcontainer/plugin-cache" -e TF_DATA_DIR="/home/vsts_azpcontainer"

stages:

- stage: destroy_addons
  jobs:
  - job: destroy_addons
    displayName: "Destroy Addons. Level 2"
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Destroy Addons
        name: destriy_addons
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Build.SourcesDirectory)/* /tf/caf && cp -r $(Build.SourcesDirectory)/.devcontainer /tf/caf/            
            cd /tf/caf/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/landingzone/
            ./scripts/deploy_level_with_rover.sh level2 aks_secure_baseline /add-ons/aks_secure_baseline_v2 
        env:
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          TF_VAR_environment: $(ENVIRONMENT)
          ACTION: "destroy -auto-approve"

- stage: destroy_aks
  jobs:
  - job: destroy_aks
    displayName: "Destroy AKS. Level 2"
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Destroy AKS
        name: deploy_aks
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Build.SourcesDirectory)/* /tf/caf && cp -r $(Build.SourcesDirectory)/.devcontainer /tf/caf/            
            cd /tf/caf/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/landingzone/
            ./scripts/deploy_level_with_rover.sh level2 aks
        env:
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          TF_VAR_environment: $(ENVIRONMENT)
          ACTION: "destroy -auto-approve"

- stage: destroy_level1
  jobs:
  - job: destroy_networking_spoke
    displayName: "Destroy Networking Spoke. Level 1"
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Destroy Networking Spoke
        name: destroy_networking_spoke
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Build.SourcesDirectory)/* /tf/caf && cp -r $(Build.SourcesDirectory)/.devcontainer /tf/caf/            
            cd /tf/caf/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/landingzone/
            ./scripts/deploy_level_with_rover.sh level1 networking_spoke
        env:
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          TF_VAR_environment: $(ENVIRONMENT)
          ACTION: "destroy -auto-approve"

  - job: destroy_networking_hub
    displayName: "Destroy Networking Hub. Level 1"
    dependsOn: destroy_networking_spoke
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Destroy Networking Hub
        name: destroy_networking_hub
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Build.SourcesDirectory)/* /tf/caf && cp -r $(Build.SourcesDirectory)/.devcontainer /tf/caf/            
            cd /tf/caf/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/landingzone/
            ./scripts/deploy_level_with_rover.sh level1 networking_hub
        env:
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          TF_VAR_environment: $(ENVIRONMENT)
          ACTION: "destroy -auto-approve"

  - job: destroy_shared_services
    displayName: "Destroy Shared Services. Level 1"
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Destroy Shared Services
        name: destroy_shared_services
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Build.SourcesDirectory)/* /tf/caf && cp -r $(Build.SourcesDirectory)/.devcontainer /tf/caf/            
            cd /tf/caf/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/landingzone/scripts/
            ./deploy_level_with_rover.sh level1 shared_services
        env:
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          TF_VAR_environment: $(ENVIRONMENT)
          ACTION: "destroy -auto-approve"
- stage: destroy_launchpad
  jobs:
  - job: destroy_launchpad
    displayName: "Destroy Launchpad"
    container: rover

    steps:
      - task: AzureCLI@2
        displayName: Destroy Launchpad. Level 0.
        name: destroy_launchpad
        inputs:
          azureSubscription: $(AZURE_SERVICE_NAME)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            cp -rs $(Build.SourcesDirectory)/* /tf/caf && cp -r $(Build.SourcesDirectory)/.devcontainer /tf/caf/                 
            /tf/caf/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/landingzone/scripts/launchpad.sh
        env:
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          TF_VAR_environment: $(ENVIRONMENT)
          ACTION: "destroy -auto-approve"