- name: Clean-up directory
  file:
    path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
    state: absent
  when: config.cleanup_destination | bool

- name: Creates directory
  file:
    path: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}"
    state: directory
  when: config.features.subscription_creation | bool

# - name: Retrieve default billing profile
#   command: "az rest --method get --uri https://management.azure.com/providers/Microsoft.Billing/billingaccounts?api-version=2020-05-01 --query \"value[?properties.agreementType=='EnterpriseAgreement'].{id:properties.enrollmentAccounts[0].id}\" -o tsv"
#   register: enrollment_account
#   when: config.billing_subscription_role_delegations.enrollment_account_name is not defined

# - debug: msg="{{enrollment_account}}"

# - name: Check enrollment account
#   fail:
#     msg: You must be connected to Azure with a user being an account owner.
#   when: enrollment_account.skipped == false and enrollment_account.stdout == ""

# - set_fact:
#     enrollment_account_name="{% if enrollment_account == '' %} {{config.billing_subscription_role_delegations.enrollment_account_name}} {% else %} {{enrollment_account}} {% endif %}"


# - debug: msg="{{enrollment_account_name}}"


- name: readme
  ansible.builtin.template:
    src: "{{ level }}/{{ base_folder }}/readme.md.j2"
    dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/readme.md"
    force: yes
  when: config.features.subscription_creation | bool

- name: subscription role delegation
  ansible.builtin.template:
    src: "{{ level }}/{{ base_folder }}/{{ item }}.tfvars.j2"
    dest: "{{ config.destination_install_path }}{{ config.destination_relative_base_path }}/{{ level }}/{{ base_folder }}/{{ item }}.tfvars"
    force: yes
  loop:
    - landingzone