apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 1.87.6
    helm:
      parameters:
        - name: rbac.enabled
          value: 'true'
      values: |-
        kubernetes.ingressClass: traefik
        kubernetes.ingressEndpoint.useDefaultPublishedService: true
    chart: traefik
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

