
- name: "set destination paths private_dns"
  set_fact:
    destination_path:  "{{ config.configuration_folders.platform.destination_base_path }}/{{ config.configuration_folders.platform.destination_relative_path }}/{{ level }}/{{ base_folder }}/private_dns/{{ environment }}"

- name: "Clean-up directory - subscription - {{ destination_path }}"
  file:
    path: "{{ destination_path }}"
    state: absent
  when: config.configuration_folders.asvm.cleanup_destination  | default(true) | bool

- name: "Load variable for resources private_dns"
  include_vars:
    name: resources
    dir: "{{config_folder}}"
    depth: 1
    ignore_unknown_extensions: true
    files_matching: "connectivity_private_dns.yaml|connectivity_private_dns.caf.yaml"

- name: "Content of resources"
  debug:
    msg: "{{resources}}"

- name: "[{{ level }} {{ folder_name }}] - {{ folder_name }} - Creates directory"
  file:
    path: "{{ destination_path }}"
    state: directory

- name: private_dns {{ environment }} - Tfvars
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ level }}/{{ base_folder }}/private_dns/*.j2"
    - "{{ level }}/{{ base_folder }}/private_dns/*.md"
